Web/ST.Web/Models/ST/STAddTicketViewModel.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using ST.SharedEntitiesLib;

namespace ST.Web.Models.ST
{
    public class STAddTicketViewModel
    {
        public Ticket Ticket { get; set; }
        public IEnumerable<SelectListItem> Severities { get; set; }

        public IEnumerable<SelectListItem> Products{ get; set; }
    }
}

Web/ST.Web/Controllers/STController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ST.SharedEntitiesLib;
using ST.SharedInterfacesLib;
using ST.Web.Models.ST;

namespace ST.Web.Controllers
{
    //[Authorize]
    public class STController : Controller
    {
        private readonly ISTAppService<ISTRepo> _stService;

        public STController(ISTAppService<ISTRepo> stService)
        {
            _stService = stService;
            Initialise();
        }

        private void Initialise()
        {
            // TODO - Configure this using the ASP.Net Core Configuration way.
            ViewBag.Environment = "TODO-Environment";
            // ViewBag.Environment = ConfigurationManager<>.AppSettings["Environment"];
        }

        public ActionResult Index()
        {
            var tickets = _stService.GetActiveTickets();

            return View(tickets);
        }
        
        [HttpPost, ValidateAntiForgeryToken]
        [Route("/AddTicket")]
        public ActionResult AddTicket([Bind(Prefix = "Ticket.ProductId")]int productId, [Bind(Prefix = "Ticket.SeverityId")]int severityId, [Bind(Prefix = "Ticket.Problem")]string problem, [Bind(Prefix = "Ticket.Description")]string description, bool active)
        {
            if (!ModelState.IsValid)
            {
                // TODO: Do more granular checks per parameter to find out what is wrong...
                ModelState.AddModelError("OneOfTheAboveParameters", "OneOfTheAboveParameters has a problem.");
                ViewBag.Message = "A critical error occured in the model binding";
                return View(new STAddTicketViewModel());
            }

            var ticket = _stService.AddTicket(
                new Ticket()
                {
                    ProductId = productId,
                    SeverityId = severityId,
                    Problem = problem,
                    Description = description,
                    Active = active
                });

            ViewBag.Message = $"Your ticket has been created.  Your ticket ID is {ticket.TicketId}";

            STAddTicketViewModel vm = GetAddTicketVm(new Ticket());

            return View(vm);
        }

        [Route("/AddTicket")]
        public ActionResult AddTicket()
        {
            var ticket = new Ticket();

            STAddTicketViewModel vm = GetAddTicketVm(ticket);

            return View(vm);
        }

        private STAddTicketViewModel GetAddTicketVm(Ticket ticket)
        {
            var severities = _stService.GetSeverities();
            var severitiesSelectItem = severities.Select(s => new SelectListItem()
            {
                Value = s.SeverityId.ToString(),
                Text = s.DisplayName
            });

            var products = _stService.GetProducts();
            var productsSelectItem = products.Select(p => new SelectListItem()
            {
                Value = p.ProductId.ToString(),
                Text = p.Description
            });

            var vm = new STAddTicketViewModel()
            {
                Severities = severitiesSelectItem,
                Products = productsSelectItem,
                Ticket = ticket
            };



            return vm;
        }

        //TODO [Authorize]
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Search(string searchTerm)
        {
            var tickets = _stService.GetActiveTicketsMatching(searchTerm);
            return View("Index", tickets);
        }

        [HttpPost]
        public ActionResult UpdateStatus(string status)
        {
            // TODO - Move the STSession into another namespace and take away the dependency between this and the API controllers
            // STSession.Status = status;
            return Ok(status);  // TODO - Fix the status
        }
    }
}

Web/ST.Web/Views/ST/AddTicket.cshtml
@using ST.SharedEntitiesLib
@using ST.Web.Models.ST
@model ST.Web.Models.ST.STAddTicketViewModel

@{
    ViewBag.Title = "Add Tickets";
}

<h2>@ViewBag.Title.</h2>

@{

    if (ViewBag.Message != null && ((string)ViewBag.Message).Contains("Your ticket has been created.  Your ticket ID is"))
    {
        <h3>@ViewBag.Message</h3>

    }
    else
    {
        using (@Html.BeginForm())
        {
            @Html.ValidationSummary(true)

            @Html.AntiForgeryToken()

            <legend>Ticket Details</legend>

            <div>
                <div>
                    @Html.LabelFor(model => model.Ticket.Description)
                    @Html.EditorFor(model => model.Ticket.Description)
                </div>
            </div>

            <div class="validation-errors">
                @Html.ValidationMessageFor(model => model.Ticket.Description)
            </div>

            <div>
                <strong>@Html.LabelFor(model => model.Products, "Product")</strong>
                @Html.DropDownListFor(model => model.Ticket.ProductId, Model.Products, null, "productId")
            </div>

            <div>
                @Html.LabelFor(model => model.Ticket.Active)
                    @Html.EditorFor(model => model.Ticket.Active, null, "active")
            </div>

            <div>
                <p class="formfield">
                    <strong>@Html.LabelFor(model => model.Ticket.Problem)</strong>
                    @Html.TextAreaFor(model => model.Ticket.Problem, 10, 100, null)
                </p>
            </div>

            <div class="validation-errors">
                @Html.ValidationMessageFor(model => model.Ticket.Problem)
            </div>

            <div>
                <strong>@Html.LabelFor(model => model.Ticket.Severity.DisplayName, "Severity")</strong>
                @Html.DropDownListFor(model => model.Ticket.SeverityId, Model.Severities)
            </div>

            <div><input type="submit" value="Create Ticket" /></div>
        }
    }
}

Web/ST.Web/Views/ST/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@supportticket.com">Support@supportticket.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@supportticket.com">Marketing@supportticket.com</a>
</address>

Web/ST.Web/Views/ST/Index.cshtml
@model ICollection<ST.SharedEntitiesLib.Ticket>

@{
    ViewBag.Title = "Support Tickets - Home";
}

<h2>View Tickets</h2>
<p><strong>Note: </strong>Inactive tickets will not be displayed</p>

<div>
    <p>
        Download the code from Github <a href="https://github.com/virasana/SupportTicket">here</a>
    </p>
</div>

<div class="row">
    <div class="col-md-12 container">
        @*<div class="well">
                @using (Html.BeginForm("Search", "ST", FormMethod.Post))
                {
                    <div><label for="searchTerm">Search</label><input id="searchTerm" name="searchTerm" type="text"/><input type="submit" value="Search" /></div>
                    <div>Note: Azure Search Index updates every 5 mins</div>
                }
            </div>*@
        <div class="well">
            @foreach (var item in Model)
            {
                <table class="table-bordered table-striped table-responsive">
                    <tr>
                        <td colspan="2"><strong>Ticket ID</strong>: @item.TicketId</td>
                    </tr>
                    <tr>
                        <td>
                            @Html.LabelFor(m => item.Description)
                        </td>
                        <td>
                            @item.Description
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.LabelFor(m => item.Problem)
                        </td>
                        <td>
                            @item.Problem
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.LabelFor(m => item.Active)
                        </td>
                        <td>
                            @item.Active
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.LabelFor(m => item.TicketId)
                        </td>
                        <td>
                            @item.TicketId
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.LabelFor(m => item.Severity.DisplayName)
                        </td>
                        <td>
                            @item.Severity.DisplayName
                        </td>
                    </tr>
                </table>
                <hr />
            }
        </div>
    </div>

</div>